// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nrs.Infrastructure.Persistence;

#nullable disable

namespace Nrs.Infrastructure.Migrations
{
    [DbContext(typeof(NrsDbContext))]
    [Migration("20260628012953_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Nrs.Domain.Entities.IdCard", b =>
                {
                    b.Property<long>("IdCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_CARD_ID");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("CARD_NUMBER");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("CARD_TYPE");

                    b.Property<string>("CivilNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("CIVIL_NUMBER");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("EXPIRY_DATE");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ISSUE_DATE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("STATUS");

                    b.HasKey("IdCardId");

                    b.HasIndex("CivilNumber")
                        .HasDatabaseName("IX_ID_CARD_CIVIL_NUMBER");

                    b.ToTable("ID_CARD", (string)null);
                });

            modelBuilder.Entity("Nrs.Domain.Entities.Passport", b =>
                {
                    b.Property<long>("PassportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PASSPORT_ID");

                    b.Property<string>("CivilNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("CIVIL_NUMBER");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("EXPIRY_DATE");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("ISSUE_DATE");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("PASSPORT_NUMBER");

                    b.Property<string>("PassportType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("PASSPORT_TYPE");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("STATUS");

                    b.HasKey("PassportId");

                    b.HasIndex("CivilNumber")
                        .HasDatabaseName("IX_PASSPORT_CIVIL_NUMBER");

                    b.ToTable("PASSPORT", (string)null);
                });

            modelBuilder.Entity("Nrs.Domain.Entities.Person", b =>
                {
                    b.Property<string>("CivilNumber")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("CIVIL_NUMBER");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATE_OF_BIRTH");

                    b.Property<string>("FamilyNameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("FAMILY_NAME_AR");

                    b.Property<string>("FamilyNameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("FAMILY_NAME_EN");

                    b.Property<string>("FirstNameAr")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("TEXT")
                        .HasColumnName("FIRST_NAME_AR");

                    b.Property<string>("FirstNameEn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("FIRST_NAME_EN");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("GENDER")
                        .IsFixedLength();

                    b.Property<string>("NationalityCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("NATIONALITY_CODE");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("PHOTO_PATH");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("TEXT")
                        .HasColumnName("STATUS");

                    b.HasKey("CivilNumber");

                    b.HasIndex("DateOfBirth")
                        .HasDatabaseName("IX_PERSON_DATE_OF_BIRTH");

                    b.HasIndex("FamilyNameAr")
                        .HasDatabaseName("IX_PERSON_FAMILY_NAME_AR");

                    b.HasIndex("FamilyNameEn")
                        .HasDatabaseName("IX_PERSON_FAMILY_NAME_EN");

                    b.HasIndex("NationalityCode")
                        .HasDatabaseName("IX_PERSON_NATIONALITY_CODE");

                    b.ToTable("PERSON", (string)null);
                });

            modelBuilder.Entity("Nrs.Domain.Entities.IdCard", b =>
                {
                    b.HasOne("Nrs.Domain.Entities.Person", "Person")
                        .WithMany("IdCards")
                        .HasForeignKey("CivilNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Nrs.Domain.Entities.Passport", b =>
                {
                    b.HasOne("Nrs.Domain.Entities.Person", "Person")
                        .WithMany("Passports")
                        .HasForeignKey("CivilNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Nrs.Domain.Entities.Person", b =>
                {
                    b.Navigation("IdCards");

                    b.Navigation("Passports");
                });
#pragma warning restore 612, 618
        }
    }
}
